### ISSUE TITLE
Monentary switches default state and jumpers.

### ISSUE THREAD

**Issue by sojastar** [jefftranter/68000#10]
Hi,

I am trying to build Rev 2.1.1 of the TS2 computer and though you provide very detailed information, I have a few questions:

1. reading the schematics and looking at the PCB, I am not a 100% sure how to solder the monentary switches. Can you confirm that the unpushed closed (I am not sure of the proper terminolgy, but I mean the contact that is closed when the switch is not pushed down) should be between pin 1 and pin 2 for SW1 (reset) SW3 (step) and SW4 (abort)?

2. do JP1 to JP4 on the Rev 2.1.1 PCB correspond to J2 in the BOM?

3. what does J1 in the BOM correspond to on the Rev 2.1.1 PCB?

Thanks for all your work streamlining these resources!

**Comment by jefftranter** [comment]
1. See the file https://github.com/jefftranter/68000/blob/master/TS2/v2/theoryofoperation.txt (near the end) for information on the switches. You are correct that pins 1 and 2 of the momentary switches are the normally closed contacts.
2. Yes, JP1 through JP4 are indicated as J2. I will correct the BOM.
3. There is no J1. I will correct the BOM.

**Comment by sojastar** [comment]
Thank you very much for your detailed answer !

**Comment by sojastar** [comment]
Sorry, I forgot to close the issue. One last thing: I see you updated the ods BOM but not the pdf version.
