### ISSUE TITLE
math error 

### ISSUE THREAD

**Issue by joelang** [jefftranter/68000#3]
I loaded a fresh copy. only changed ACIA and RAM addresses

Simple example of the issue

23056 Bytes free

Enhanced 68k BASIC Version 3.52

Ready
PRINT 6*6
 36

Ready
PRINT 6^2
 191.7739

Ready
it doesn't occur for all values:

10 FOR A=1 TO 10
20 PRINT A,A^2
30 NEXT A

RUN
 1             1
 2             4
 3             47.94347
 4             16
 5             95.87441
 6             191.7739
 7             191.7488
 8             64
 9             383.4976
 10            383.4976

Ready

It's homebuilt hardware so I replicated the issue on another system I built 3 decades ago.  Same result.

I'm not a 68k wizzard, no idea where to look.
It would be interesting to see if the 6502 basic has the same error
(i don't have a 6502 to try it on)

joe lang

**Comment by jefftranter** [comment]
I can confirm that this bug is not present in the 6502 version (but it is a very different code base).

**Comment by jefftranter** [comment]
And I can confirm that I see it in the 68000 version on my hardware.

**Comment by jefftranter** [comment]
I've been able to  determine the following:
The code for exponentiation (^) is in the source at label LAB_POWER.
It internally calculates X^Y using EXP(LOG(X)*Y).
The LOG() function appears to be correct but the EXP() function often returns incorrect values.
The EXP() code is in the source at label LAB_EXP.
Unfortunately, the code is very complex (CORDIC algorithm and hyperbolic arctan tables, anyone?) and the original other is no longer around, so this bug will be hard to fix. It  is not clear if it ever worked or if it might have always been there in the 68000 version.

**Comment by joelang** [comment]
I have the answer. but I don't know how to add it to the project.

Constants in  TAB_HTHET and KFCTSEED are incorrect.
it's the result of the vasm ">>" operator. It appears to be signed.
I don't see any reason for the "constant>>n" syntax so i removed it.
Here's the fixed table:

* constants are normalised to n integer bits and are tanh(2^-i)
n       equ     2
TAB_HTHET
        dc.l    $2327d4f4                       * atnh(2^-1)    .549306144
        dc.l    $1058aefa                       * atnh(2^-2)    .255412812
        dc.l    $080ac48e                       * atnh(2^-3)
        dc.l    $04015622                       * atnh(2^-4)
        dc.l    $02002ab0                       * atnh(2^-5)
        dc.l    $01000554                       * atnh(2^-6)
        dc.l    $008000aa                       * atnh(2^-7)
        dc.l    $00400014                       * atnh(2^-8)
        dc.l    $00200002                       * atnh(2^-9)
        dc.l    $00100000                       * atnh(2^-10)
        dc.l    $00080000                       * atnh(2^-11)
        dc.l    $00040000                       * atnh(2^-12)
        dc.l    $00020000                       * atnh(2^-13)
        dc.l    $00010000                       * atnh(2^-14)
        dc.l    $00008000                       * atnh(2^-15)
        dc.l    $00004000                       * atnh(2^-16)
        dc.l    $00002000                       * atnh(2^-17)
        dc.l    $00001000                       * atnh(2^-18)
        dc.l    $00000800                       * atnh(2^-19)
        dc.l    $00000400                       * atnh(2^-20)
        dc.l    $00000200                       * atnh(2^-21)
        dc.l    $00000100                       * atnh(2^-22)
        dc.l    $00000080                       * atnh(2^-23)
        dc.l    $00000040                       * atnh(2^-24)
        dc.l    $00000020                       * atnh(2^-25)
        dc.l    $00000010                       * atnh(2^-26)
        dc.l    $00000008                       * atnh(2^-27)
        dc.l    $00000004                       * atnh(2^-28)
        dc.l    $00000002                       * atnh(2^-29)
        dc.l    $00000001                       * atnh(2^-30)
        dc.l    $00000000                       * atnh(2^-31)
        dc.l    $00000000                       * atnh(2^-32)

KFCTSEED        equ     $26A3D110               * $26A3D110

**Comment by jefftranter** [comment]
This looks great!
I will look into updating the code with these changes and testing it out.

**Comment by jefftranter** [comment]
The fix works and was applied to the code.
Thanks!
